version: '3.9'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    # command: mongod --smallfiles --logpath=/dev/null

  mipt_crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mipt_crawler
    volumes:
      - ./src:/app
    depends_on:
      - db

volumes:
  mongodb_data_container:
