version: '3.9'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mipt_crawler:
    build: .
    volumes:
      - mipt_crawler_data_container:/results

volumes:
  mongodb_data_container:
  mipt_crawler_data_container:
